name: Node.js CI
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install typescript globally
        run: npm install -g ts-node

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hemakanth-repo:latest

      - name: Deploy to Heroku
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
          with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "Hemakanth_User_Service" #Must be unique in Heroku
          heroku_email: "hkanth098@gmail.com"
          usedocker: true
